name:                butter
version:             0.0.5.1
github:              "System-Indystress/Butter"
license:             BSD3
author:              "Matthew Ahrens"
maintainer:          "matt.p.ahrens@gmail.com"
copyright:           "2018 SID.run"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on Github at <https://github.com/System-Indystress/Butter#readme>

dependencies:
- base < 5
- forkable-monad
- transformers
- text
- aeson
- stm
- containers
- template-haskell
- free
- network-simple


library:
  source-dirs: src

# executables:
#   Butter-exe:
#     main:                Main.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - Butter

tests:
  Lang-test:
    main:                Main.hs
    source-dirs:         test/first
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - butter
    - HUnit
  Protocol-test:
    main:                Main.hs
    source-dirs:         test/protocol
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - butter
    - HUnit
