name:                butter
version:             0.1.0.4
github:              "System-Indystress/Butter"
license:             BSD3
author:              "Matthew Ahrens"
maintainer:          "matt.p.ahrens@gmail.com"
copyright:           "2018 SID.run"
category:            Distributed Computing, Concurrency
synopsis:            Monad Transformer for Asyncronous Message Passing
description: <          A Monad Transformer for spreading arbitrary Monadic computation
                     across several processes using Erlang+OTP inspired conventions.

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on Github at <https://github.com/System-Indystress/Butter#readme>

dependencies:
- base < 5
- transformers
- text
- aeson
- stm
- containers
- template-haskell
- free
- network-simple
- bytestring
- HUnit
- forkable-monad >= 0.2.0.0


library:
  source-dirs: src

# executables:
#   Butter-exe:
#     main:                Main.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - Butter

tests:
  Lang-test:
    main:                first/Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - butter
    - HUnit
  Protocol-test:
    main:                protocol/Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - butter
    - HUnit
